### ISSUE TITLE
Monopoly

### ISSUE THREAD

**Issue by koreansovereignwealthfund** [district0x/district-proposals#155]
Can we have a system where people can buy and sell districts? If and when there are hundreds of districts with function and revenue, it would be neat to be able to buy them and sell them like they're actual companies.

**Comment by mckmuze** [comment]
I will be closing this because it doesn't not adhere to the proposal standards outlined here: https://github.com/district0x/district-proposals

Also, keep in mind this would be difficult because a decentralized system is not really owned by a single person so buying and selling them like a company is not really possible but if you can give clear examples of how this would work I would love to see if I'm missing something here.
