### ISSUE TITLE
DP-16: Service for sharing stuff

### ISSUE THREAD

**Issue by uvizhe** [district0x/district-proposals#16]
# Name
Service for sharing stuff

# Purpose
In our consumer society everyone possess a lot of stuff most of which just gather dust on shelves most of the time. If someone needs a screwdriver for one-time need it's odd to go and buy one when her neighbor next floor already has it and is willing to give it for a couple of hours. Sharing is good both in terms of economic and environment costs and as a socialization driver.

Starting with just a simple service we can end up with a cultural phenomenon where people prefer to store all their shared stuff in a special semi-public spaces thus freeing their home space from 'useless' stuff. Or we can come to the entirely shared economy who knows.

# Description
The service idea fits perfectly *district0x* in my opinion.

* There's a listing of things users are willing to share.
* There's a place for smart contracts as it's natural for stuff owners to ask (in some cases) for a deposit for their property and smart contracts can store that deposit until a borrowed thing comes back.
* There's a user reputation which also guarantees a fair play.
* Maybe an optional user verification for even higher security.
* And of course there should be a search box to find a nearby offers.

Here I stop my description. I have a more detailed view but IMO for the proposal that's enough.

// my slack username is **uvizhe**

**Comment by joeyurgz** [comment]
We envision district0x being a perfect home for sharing districts, this is very much in line with what we hope to see!

**Comment by lkngtn** [comment]
I had an interesting conversation with @miguel.marques on slack regarding a local community resource sharing concept he is working on that he is calling [MyFamily](http://www.apraca.net/in-english/myfamily/). The premise is to organize groups of people who can pool and share resources.

**Comment by uvizhe** [comment]
@lkngtn thanks for this reference! That's an interesting project though I'm not sure if it reflects what I want to build. Different countries and regions have different social culture and my context is somehow differs for their but anyway it's a huge pool of new ideas.

As of high value items I agree these assets are even better for sharing. I see two ways here: either MyFamily approach when some virtual community buys and shares this stuff or the second way is to let users to set some renting fee so their investments can return a bit faster or just get possible to return.

**Comment by Coke-in** [comment]
Great Idea. i like it a LOT.

Guys keep in mind that this "kind of facebook" but for neighbors is exploding.
"Land" a screwdriver to someone who lives in your same building or next to it will be super.
Having a place where people can put the things to borrow/loan would be super! :)

I also add the following ideas:
- when u took the "screwdriver" you pay some DNT tokens that will be release when you return the object.. BUT
 - Not all of them, since it would be easy for someone to use the blender, for example, broke it, and then put it back in place and the next one will find it unusable. 
So, the DNT payed for the "borrow", i suggest, would be release when the next guy will borrow such object so he can prove the tool is still working/usable (we can play on the percentage of returning the object in first place, and the one to keep "locked" until is taken again by someone).

Also we could think to have some place where to store such things, with a door usable with Secure Identity so whoever accessing the perimeter will be recorded in the blockchain and if something is broken/missing, it will be pretty easy to address who was and when :)

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
