### ISSUE TITLE
City0x1 – Contribute your district proposal here and let's build a city together

### ISSUE THREAD

**Issue by Qryptoc** [district0x/district-proposals#160]
Name:          City0x1 – Contribute your district proposal here and let's build a city together
Proposal:      Many great proposals, let's work together!?

**Description**
Currently, **+150 district0x proposals make it a daunting task to read and vote for all proposals**. Furthermore, the voting system only allows proposers to compete for one district to be build, whereas working together could be much more fruitful long term. The idea is that many of the proposals can complement one another and make each other stronger. 

Therefore, **I call upon all proposers to collaborate on grander visions of a city in which their individual district would thrive**. For example, if you have a car sharing district, why not search for a payment district, or an insurance district and see how you could complement one another? Or when you are reading about another district and a creative idea pops into your head of how your district could extend this, why not suggest your idea to the other district? Who gets which reward/tokens, what needs to be build first, etc. can be organically grow/be discussed within the proposal. 

For City0x1, I will use my [own proposal The New Market](https://github.com/district0x/district-proposals/issues/140). **My hope is to work together with 4-6 other districts** who I will be reaching out to in their comment sections, proposers can also comment within this City0x1 proposal for collaboration. 

This is of course an experiment from me as one of the proposers, feel free to propose your own City0x. 
**Proposers, unite!**

**Comment by finepettingduck** [comment]
Check out my proposal for a community exploration and hospitality district! I feel like it could fit really well into the city framework you're proposing. 

Link is here: https://github.com/district0x/district-proposals/issues/157

Great idea, by the way.

**Comment by basiccrypto** [comment]
Another great idea I think encouraging collaboration and finding where synergies make districts better together will enhance the quality of offerings across the board and provide larger potential markets if this is done smartly/correctly.  After reading many of these proposals and watching Brady's (@mckmuze) live stream it is clear that the education proposals as well as the freelance/contractor proposals could find common ground among themselves and build a district with larger network effects.

Based on the brainstorming of #140 I put together the following proposal #162 to help start this conversation of this complex question.

**Comment by Bradymck** [comment]
Just a heads up. I just setup the proposal tags, almost done tagging everything. This is a work in progress but you may be able to use this for collaboration to make things easier here.

**Comment by Bradymck** [comment]
Just a heads up. I am doing some thinking about collaboration and better ways we can address this. I am however going to be closing this out because the voting app already has a lot to go through for people wanting to vote. I do really appreciate you doing this though but I think we need a better approach to encourage collaboration and it needs to be simple. I think this was a bit overwhelming even for me to think of how this would work in practice. I did leave it up to see if there was traction though but considering there was little I think we need a different game plan. Reach out to me if you have other ideas though. I think this was a step in the right direction but we should keep the voting app clean. I will be doing more cleaning up in here going forward as well. If we can get a standardized approach for how this will work I will  let the community know and update everyone accordingly.
