### ISSUE TITLE
District Proposal: A market for ethereum identicons.

### ISSUE THREAD

**Issue by crazygorilla** [district0x/district-proposals#2]
Name: Blockies Bazaar
Purpose: This district will enable users to openly exchange "identicons" or "blockies" associated with Ethereum addresses.
Description: When sending ETH, or any other tokens under Ethereum, identicons act as visual confirmation of the verity of the receiving address to prevent mistakenly sending a significant amount of one's fortune to the wrong address; a tragic, irrevocable error. For this reason, one may conclude that the possession of an easily identifiable identicon is desirable and, perhaps to some, necessary. Others may also be interested in "vanity identicons" which look strikingly similar to faces, animals, items in popular media, or any other recognizable image. In Parity, you can generate a line of identicons at once to facilitate your search for something of your liking. However, it takes time to find anything even remotely interesting. Hence, in order to supply this demand, there is value in establishing the Blockies Bazaar District.
In this district, users can generate identicons that can be sold without compromisinng the identity of the identicons. After users generate what they deem to be a good identicon, they can choose to use it for themselves, or have it be listed for purchase. The public and private keys associated with listed identicons will be hidden and sealed; neither the buyer or the seller or the generator. Once they choose to open it, it can no longer be listed in the market.

**Comment by mckmuze** [comment]
This lends well to the identity issues in our day and age. It seems we are in a bit of an identity crisis as a whole generation. The global distributed reality will require creative ways to address identity and anonymity in a way that will secure things enough to "trust" someone yet not compromise our security. 

This would be interesting if you associated the address with your[Keybase](https://keybase.io/) account, this I feel is the best solution to our (hopefully) temporary global identity crisis. Some kind of unique visual aid like an 'identicon' may help here. 

I'm curious how difficult it would be to use any kind of media file. Audio, video, gif, etc. If this was the case, you could register the master copy of a musical work just as easy as an emoticon. You could also connect this key pair to Keybase as an added layer of security. 

This essentially could make any content you have created an identity verification opportunity with the dual function of establishing a beneficiary to a specific work. Interesting idea. Thanks for sharing!

**Comment by lkngtn** [comment]
A slack user brought up the use case of creating a decentralized directory of PGP addresses the other day and I thought that it was a really cool idea. Perhaps the Name Bazaar concept could be expanded to allow the purchase and trading of any sort of unique identifier to address mapping. 

For the Blockies/Identicons use case in particular there is the unique challenge of not knowing ahead of time what you want since they are randomly generated, just that you want it to look cool/memorable.

 In that case there is a value for curation and categorization, so perhaps it could borrow some of the aspects of the curation market as well. Users could generate new blockies, evaluate them and then choose to buy into them or not, additional users could also buy in to ones they like causing it to be displayed and priced higher and then eventually a user would purchase the blocky and the purchase price would go to people that are "invested" in the blocky as part of the curation process.

I do have to say though, this is a problem that I've never really thought about before as I've only ever used those icons as check-sums to validate that the address I copy pasted is correct and would not have occurred to me to seek out, let alone pay for a special one.

**Comment by okmrponcho** [comment]
1) Just technically speaking is this feasible? Person A is generating public keys (and presumably private keys) on his machine, and somehow transferring the private keys to Person B without ever having information about that very key? Any initial thoughts on how that could work?

2) Would be cool if you could "design" the icon. Like almost in MS paint, drawing the pixels yourself. You could make some cool artwork :-)

**Comment by mckmuze** [comment]
@okmrponcho I'm curious, on a technical level, about these types of concepts in general. I had the same question about the 'Name Bazaar'. The transfered items would need to "tokenized" to make it work right so you can transfer it. This rolls into the same category as memes, names and in this case 'Blockies'.

**Comment by AngeloAdam** [comment]
@crazygorilla please send me a direct message on slack @angelo. thanks

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
