### ISSUE TITLE
Publish0x - A Decentralised Publishing Market for Books

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#214]
## **Publish0x - A Decentralised Publishing Market for Books**: 
Created by @aongxa

## **Purpose**: 
To allow authors to self-publish books, articles, and newspapers and to decentralize the process of creation. The platform would include a built-in e-reader to reach millions of readers easily. Similar to Amazon Kindle, users are free to download a sample of the work before purchasing. All payments to be made in DNT or ETH. Works are curated through a  ranking mechanism.

Similar to how Amazon disrupted publishing in the physical world by introducing the Kindle system, this platforms aims to disrupt centralized e-book publishers such as the Kindle by providing a platform to authors. Authors who currently publish on other platforms are encouraged to self-publish on this platform. 

## **Description**: 
Authors can keep control of rights to their work and set their own list prices. Authors can also upload documents in several formats. Make changes to your published items at any time. 

_"In a December 5, 2009 interview with The New York Times, Amazon CEO Jeff Bezos revealed that Amazon keeps 65% of the revenue from all e-book sales for the Kindle. The remaining 35% is split between the book author and publisher.  After numerous commentators observed that Apple's popular App Store offers 70% of royalties to the publisher, Amazon began a program that offers 70% royalties to Kindle publishers who agree to certain conditions."_

It is proposed that Publish0x offers a higher degree of royalty to authors in order to provide a better platform than centralized organisations such as Amazon. This might result in savings for consumers and better value or authors. Works are protected through blockchain authentication systems (similar to DRM) to protect intellectual property.

## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by PerryEdu** [comment]
I think you have a great idea. It is time for some real competition to Amazon and Kindle.
With regard to authors - they receive very little of the royalty with traditional publishing and for this reason, very few authors can make a living from writing. Maximum royalties could change this and enable many more talented writers to live their dream.
Your proposal has huge potential. I would vote for it.
Let me know what you think of my proposals - all the best

**Comment by RMBLRX** [comment]
Just a few thoughts that I brought up to Publica, but could also apply here (since they may have fallen on deaf ears over there anyway):

Most forward-thinking publishing platforms of all stripes allow for paying extra in any given sale by way of a slider.  As far as I'm aware, most if not all of these platforms offer a flat royalty rate from any extra that's given, just as they do from the list price.  One area where a decentralized publishing platform could stand out is in either giving the author 100% of any extra paid above their set minimum or, alternatively, formulated by some sort of a weighted average of amount paid across all sales (weighted, for instance, by recency and frequency of sales) with the royalty rate for that extra amount paid increased on a curve from the minimum to that average (the district takes less of any extra paid, the more that's voluntarily paid).  This average would be publicly visible on the slider, but perhaps the author could also recommend a price above a minimum and have that average only visible if it falls above that recommendation.  The amount of royalties paid to the author should also be visible.  Theoretically, this should encourage patrons to pay increasingly more above the average in order to push that average as well as how much pay-out goes to the author.

The idea there is that any extra paid above what's required is likely owed to the author's own publicity efforts and merits and amounts to a tip, but doing so on a curve could serve to, both, prevent authors from abusing the system and giving the district as little as possible (bear in mind that I'm not entriely familiar with how districts work, but I do imagine that they need to pay their own way somehow) and to take some reward for upkeep of the tools which make this possible.  Royalty rates would be plenty competitive at 90% for the minimum price listed, particularly with being able to make even more on top of that.

Iterative releases should also be possible so that books could be offered in a serial or early-access manner, allowing for the possibility of a lean publishing approach that could potentially be tied to something like an ICO or whatever other sort of crowdfunding/patronage reward scheme.  Ideally, when reading through the district's own ereading platform, readers should be able to highlight and make comments (or even corrections) on the text that could be pushed to the author (how or whether the author receives these should be up to the author of course) in order to allow for crowdsourced editing as either an ongoing or privileged (for early adopters, for instance) feature.

Aftermarket sales should also be possible through platform as an alternative to refunds.  This could be done in such a way that either the reader can simply put the book up for sale and get a predetermined portion of the next sale made (predetermined by the author at the time of sale, making it possible to have the book marketed or even sold by a third party for a cut of the sale using unique links of something; either way the author gets a percentage).  This would also allow the author to change the minimum price after the fact and give earlier adopters a reward by dropping, say, an extra copy (or portion of a copy?) to them which they could either resell or give away.

Also, DRM-free listings should be optional as some authors might find this preferable.  Those listings should still be tokenized but with that token enabling a download of the book in various formats.  Holding the token should be the crucial thing, as there could be some benefit to doing so (i.e., the aforementioned iterative releases or the drops of extra copies or, hypothetically, as a "badge" of sorts with even the possibility of some special privileges entailed) vs obtaining a pirated copy of the book, itself.

**Comment by RMBLRX** [comment]
Oh, absolutely this could work for all sorts of content. It has crossed my mind that there's plenty of potential overlap, but I do imagine books being the easiest place to start.

To be clear though, the badge/tokenization thing is nothing new, but I do believe it's emerging as crucial standard in this space. What's to be done with badges, however, is still a wide open field, and I think you're on to something with unlocking portions of a website; my mind immediately went to web forum access. Discounts on physical copies or future works is another possibility. Access to special events is another (there could be cut-off periods for which tokens qualify, usually associated with a defined crowdfunding period, I imagine).

This would give those tokens value beyond the work itself. This could be used for marketing campaigns later on, as well, by having a particular reward for all books purchased before an announced cut-off date or something.

**Comment by aongxa** [comment]
@Bradymck Please reconsider status of this as I am keen to continue contributing to D0X.
