### ISSUE TITLE
Push Notification Vote Module

### ISSUE THREAD

**Issue by grasponcrypto** [district0x/district-proposals#284]
## **Name**: 
Push Vote

## **Purpose**: 
Allow voting via html5 push notifications with as few clicks as possible.

## **Description**: 
Push html5, or other, notification to app or desktop when a new 'vote' is up to all members of a district with the ability to click the notification and cast their vote directly from the notification (extra clicks likely necessary to sign the message).

## **Ethereum Address**:
grasponcrypto.stronghodl.eth

**Comment by akimc** [comment]
Hello Grasponcrypto ! This is a good idea for the higher level governance of District0x but this wouldn't qualify itself has a district I think since this isn't a "marketplace" per se. I am pretty sure Brady will chime in and explain more in detail how the actual system is going to be implemented in [Aragon](https://aragon.org/)

Meme Factory being shipped a few hours ago, after the big marketing push I am pretty sure that the team will inform us more about the next phases of how DNT holders can participate in this process. 

I could totally see a notification system for people wanting to actively participate in the ecosystem and they will probably implement delegate voting too (Liquid Democracy) so you could give your vote to someone that is very involve and share your principles.

Thanks for sharing the idea, see you in the discord !
A.

**Comment by Bradymck** [comment]
@akimc is correct, this is not really a district as it has no marketplace function. Happy to elaborate on how Aragon will function, however the District Registry will be live soon and can be seen first hand.
