### ISSUE TITLE
How do I vote and stake successfully? Metamask is funded with both ETH and DNT. Why won't it just let me vote?

### ISSUE THREAD

**Issue by ghost** [district0x/district-proposals#311]
How do I vote and stake successfully? Metamask is funded with both ETH and DNT. Why won't it just let me vote?

_Originally posted by @virtuals-usa in https://github.com/district0x/district-proposals/issues/307#issuecomment-812680352_

**Comment by virtuals-usa** [comment]
Completely useless. You can't fund with DNT, you can't fund with ETH. Never enough funds because I'm always just a little short of what's needed. Needed 10,000 DNT - put enough ETH for 17,000 DNT and still not able to fund this mess. Always some script error and there is no 'staking' now it's a straight up 10,000 DNT bill PLUS double whatever amount in DNT to do the transaction that never goes through. No wonder people despise crypto - no consistency and always a ripoff.
