### ISSUE TITLE
DP #45: Token News

### ISSUE THREAD

**Issue by eragnew** [district0x/district-proposals#45]
## Name

**Token News**

## Purpose

To create an online community centered around the curation of high-quality content related to Ethereum and the projects being built in the Ethereum ecosystem.

#### Background

I've been a regular reader of Hacker News (https://news.ycombinator.com/) for about 10 years now, and I think it's a great source of information for people who are "generally technical". People can submit links or create discussion posts, usually about programming or technology in general (although other topics show up regularly, such as science, literature, art, economics, etc.), and then other users can upvote particular submissions or post comments. I think the quality of the discussion is usually very high, much better than what you find in many other online communities.

The downside, in my view, is that there is a lot of skepticism around Ethereum, token-based sales and projects, and cryptocurrencies generally in many of the comments I've seen. And that's fine - people are entitled to their own opinions. But I think it would be great to have another online community, built in the same spirit, but with a focus on Ethereum and what I think is an amazing ecosystem being built around it.

Reddit is one source for such information, but the problem I have with that is that the Ethereum-related communities on Reddit are fractured - traders spend their time on r/ethtrader, miners spend their time on r/EtherMining, others spend time on r/ethdev or r/ethlaw, etc. General discussion takes place on r/ethereum, but many posts generate very little discussion. And pretty much every Ethereum-related project has its own subreddit, but that just results in further community fragmentation.

#### Proposal

What I propose is a simple web app, in the vein of Hacker News, where users can submit links or create discussion posts on anything Ethereum-related. The homepage would be a "leaderboard" of the top, say, 25 stories at that given time, based on an algorithm that considers things like the submitter's reputation score, upvotes from other members, time since original submission, etc. And every post can be commented on, with nested comment trees like Hacker News and Reddit. Obviously the idea here is not original - the goal is simply to create a new community with high community standards that is Ethereum-focused.

I believe this idea could be a good fit for a district0x district. The original members of the district could act as the initial moderators for discussions on the site, and new members could become moderators over time. A token mechanism or a reputation scoring system could be used as a governance layer. And ideally the site would be as integrated into the Ethereum ecosystem and web3 as possible - perhaps the static files for the site itself could be hosted in IPFS or Swarm, and there could be wallet integration if some sort of token does end up being used.

#### Note

Token News is a pretty generic name, so I'm open to other ideas if anyone has a suggestion! Feedback welcomed.

`@ragnu` on Slack

**Comment by lkngtn** [comment]
I need a decentralized or distributed (ie opensource and many people can run nodes) reddit/hackernews style interface for 1Hive and Hive Commons. The tricky part is the economic and tokens aspects which are not covered here but I would love to hear your thoughts. 

I think using a curation market like the Funding Platform proposal to create sub-communities, and then the tokens from that curation market used as stake to currate content within the community makes a lot of sense. I envision a "consensus" prediction market where members in the sub-community can bet their tokens on whether an issue should be seen by the wider/less engaged community. Members that participate but do not "bet" would serve as oracles for the prediction market. 

This would create, I think, a more compelling incentive and curation model than reddit/hacker news and would be particularly useful in the context of DAO based governance. 

If your interested in the hearing more about 1Hive or Hive Commons -- I'd recommend starting reading my intro post: https://medium.com/hive-commons/introducing-hive-commons-95dad77814bb

**Comment by crowdedconscious** [comment]
I would be very interested in playing a role in further developing a "Token News" district - was about to propose something similar, but more expanded upon. I own the ENS domain names below and would be interested in sub-leasing domains to the district in order to service others in the ecosystem.
- MediaOutlet.eth
- Contributors.eth
- MediaKit.eth
- Press-Release.eth

For example,
if I'm a user within the TokenNews District, I will have the subdomain address for transactions:
- CrowdConscious.TokenNews.MediaOutlets.eth

You to be able to launch automated press releases want to all Token News district subscribers? 
- CrowdConscious.TokenNews.Press-Release.eth
Would be cool to include a submission form with required format to go through the automated press release service. 

Want to pay contributors for their work? conversion/per-view/impression/submission?
- CrowdConscious.TokenNews.Contributors.eth

**Comment by mckmuze** [comment]
@crowdedconscious  Can you elaborate on how the automated press release feature would work? I'm having trouble conceptualizing your vision. Also can you elaborate on how the transactions would flow and why they couldn't go directly to the contributor's ENS name rather than through yours. Is it so you can create a smart contract to automate payment splitting or some other mutually beneficial model?

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
